package cyoa

type Story map[string]AutoGenerated
type AutoGenerated struct {
	Title      string    `json:"title"`
	Paragraphs []string  `json:"paragraphs"`
	Options    []Options `json:"options"`
}
type Options struct {
	Text    string `json:"text"`
	Chapter string `json:"chapter"`
}
